# apiVersion: v1
# kind: Pod
# metadata:
#   name: niels-test-container-hook2
# spec:
#   containers:
#   - name: runner
#     image: summerwind/actions-runner-dind:latest
#     command: ["sh", "-c", "while true; do sleep 1; done"]
#     securityContext:
#       privileged: true

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-admin
rules:
- apiGroups: [""]
  resources: ["pods", "jobs", "pods/log", "pods/exec", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-admin-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role
  name: pod-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: niels-test-container-hook2-work
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
  storageClassName: aws-efs