name: CI - Build & Test
on:
  pull_request:
    branches:
    - '*'
    paths-ignore:
    - '**.md'
  workflow_dispatch:
jobs:
  container-test-job:
    runs-on: self-hosted
    container:
      image: node:14.16
      env:
        NODE_ENV: development
    steps:
      - name: Hello world
        run: echo "hello world"